import * as fs from 'fs'
import * as path from 'path'
import { load } from 'js-yaml'
import { fileURLToPath } from 'url'

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)))
const compendiumsDir = path.join(root, 'compendiums')

function substitute (template, vars) {
  return template.replace(/\{\{(\w+)\}\}/g, (_, key) => vars[key] ?? '')
}

function loadManifest () {
  return load(fs.readFileSync(path.join(compendiumsDir, 'macro-manifest.yaml'), 'utf8'))
}

function loadTemplates () {
  return load(fs.readFileSync(path.join(compendiumsDir, 'template.yaml'), 'utf8'))
}

function main () {
  const manifest = loadManifest()
  const templates = loadTemplates()
  const { display } = manifest
  const docs = []

  for (const folder of manifest.folders) {
    docs.push(substitute(templates.folder.trimEnd() + '\n', {
      _id: folder._id,
      name: folder.name,
      color: folder.color
    }).trimEnd())
  }

  const reset = manifest.reset
  docs.push(substitute(templates.reset.trimEnd() + '\n', {
    _id: reset._id,
    name: reset.name,
    img: reset.img
  }).trimEnd())

  for (const row of manifest.random) {
    docs.push(substitute(templates.random.trimEnd() + '\n', {
      _id: row._id,
      folder: row.folder,
      img: row.img,
      culture: row.culture,
      gender: row.gender,
      target: row.target,
      genderLabel: display.gender[row.gender],
      cultureLabel: display.culture[row.culture],
      targetLabel: display.target[row.target]
    }).trimEnd())
  }

  const header = '# Generated by npm run macros-generate — do not edit by hand\n'
  const body = docs.join('\n---\n') + '\n'
  fs.writeFileSync(path.join(compendiumsDir, 'en-macros.yaml'), header + body, 'utf8')
  console.log('Wrote compendiums/en-macros.yaml', docs.length, 'documents')
}

main()
